export const OBJECT_TRANSLATIONS = {
    "binder": "活页夹",
    "bookshelf": "书架",
    "bow tie": "领结",
    "computer keyboard": "键盘",
    "computer mouse": "鼠标",
    "filing cabinet": "档案柜",
    "nail": "钉",
    "pencil box": "铅笔盒",
    "pencil sharpener": "卷笔刀",
    "printer": "打印机",
    "rubber eraser": "橡皮擦",
    "ruler": "尺",
    "tick": "勾",
    "tie": "领带",
    "laptop": "笔记本电脑",
    "ant": "蚂蚁",
    "antelope": "羚羊",
    "armadillo": "犰狳",
    "bear": "熊",
    "bee": "蜜蜂",
    "bird": "鸟",
    "butterfly": "蝴蝶",
    "camel": "骆驼",
    "cattle": "牛",
    "centipede": "蜈蚣",
    "dog": "狗",
    "domestic cat": "家猫",
    "dragonfly": "蜻蜓",
    "elephant": "大象",
    "fox": "狐狸",
    "frog": "青蛙",
    "giant panda": "大熊猫",
    "goldfish": "金鱼",
    "hamster": "仓鼠",
    "hippopotamus": "河马",
    "horse": "马",
    "isopod": "等足目动物",
    "jellyfish": "水母",
    "koala bear": "树袋熊",
    "ladybug": "瓢虫",
    "lion": "狮子",
    "lizard": "蜥蜴",
    "lobster": "龙虾",
    "monkey": "猴子",
    "otter": "水獭",
    "person": "人",
    "porcupine": "豪猪",
    "rabbit": "兔子",
    "red panda": "小熊猫",
    "scorpion": "蝎子",
    "seal": "海豹",
    "sheep": "绵羊",
    "skunk": "臭鼬",
    "snail": "蜗牛",
    "snake": "蛇",
    "squirrel": "松鼠",
    "starfish": "海星",
    "swine": "猪",
    "tiger": "老虎",
    "turtle": "海龟",
    "whale": "鲸鱼",
    "zebra": "斑马",
    "power drill": "电钻",
    "screwdriver": "螺丝刀",
    "stethoscope": "听诊器",
    "stretcher": "担架",
    "syringe": "注射器",
    "axe": "斧头",
    "chain saw": "链锯",
    "hammer": "锤",
    "neck brace": "颈托",
    "tv or monitor": "监视器",
    "crutch": "拐杖",
    "airplane": "飞机",
    "bicycle": "自行车",
    "bus": "公交车",
    "car": "汽车",
    "golfcart": "高尔夫球车",
    "motorcycle": "摩托车",
    "snowmobile": "雪地机车",
    "snowplow": "扫雪车",
    "train": "火车",
    "unicycle": "独轮车",
    "watercraft": "船只",
    "traffic light": "交通灯",
    "accordion": "手风琴",
    "banjo": "五弦琴",
    "cello": "大提琴",
    "chime": "编钟",
    "flute": "笛子",
    "french horn": "圆号",
    "guitar": "吉他",
    "harmonica": "口琴",
    "harp": "竖琴",
    "maraca": "沙锤",
    "oboe": "双簧管",
    "piano": "钢琴",
    "saxophone": "萨克斯管",
    "trombone": "长号",
    "trumpet": "喇叭",
    "violin": "小提琴",
    "drum": "鼓",
    "brassiere": "胸罩",
    "face powder": "散粉",
    "lipstick": "口红",
    "maillot": "女式泳装",
    "miniskirt": "超短裙",
    "perfume": "香水",
    "purse": "女式手提袋",
    "baby bed": "婴儿床",
    "backpack": "背包",
    "band aid": "创可贴",
    "beaker": "烧杯",
    "bench": "板凳",
    "bowl": "碗",
    "can opener": "开罐器",
    "cart": "推车",
    "chair": "椅子",
    "cocktail shaker": "调酒器",
    "coffee maker": "咖啡机",
    "corkscrew": "开瓶器",
    "cup or mug": "马克杯",
    "diaper": "尿布",
    "digital clock": "数字时钟",
    "dishwasher": "洗碗机",
    "electric fan": "电风扇",
    "flower pot": "花盆",
    "frying pan": "平底锅",
    "hair dryer": "电吹风",
    "hair spray": "发胶",
    "iPod": "iPod",
    "ladle": "长柄勺",
    "lamp": "灯",
    "microphone": "麦克风",
    "microwave": "微波炉",
    "milk can": "牛奶罐",
    "pitcher": "大水罐",
    "plastic bag": "塑料袋",
    "plate rack": "餐具架",
    "refrigerator": "冰箱",
    "remote control": "遥控器",
    "salt or pepper shaker": "调料瓶",
    "soap dispenser": "给皂器",
    "sofa": "沙发",
    "spatula": "小铲",
    "stove": "火炉",
    "strainer": "过滤器",
    "table": "桌子",
    "toaster": "烤箱",
    "vacuum": "吸尘器",
    "waffle iron": "华夫饼干烤模",
    "washer": "洗衣机",
    "water bottle": "水瓶",
    "wine bottle": "酒瓶",
    "bow": "蝴蝶结",
    "hat with a wide brim": "宽缘帽",
    "helmet": "头盔",
    "ray": "光线",
    "sunglasses": "太阳镜",
    "tape player": "磁带机",
    "bagel": "百吉饼",
    "burrito": "墨西哥卷饼",
    "cream": "奶油",
    "guacamole": "鳄梨色拉酱",
    "hamburger": "汉堡",
    "hotdog": "热狗",
    "pizza": "比萨饼",
    "popsicle": "棒冰",
    "pretzel": "椒盐脆饼",
    "dumbbell": "哑铃",
    "balance beam": "平衡木",
    "baseball": "棒球",
    "basketball": "篮球",
    "bathing cap": "游泳帽",
    "croquet ball": "槌球",
    "golf ball": "高尔夫球",
    "horizontal bar": "单杠",
    "ping-pong ball": "乒乓球",
    "puck": "冰球",
    "punching bag": "吊袋",
    "racket": "球拍",
    "rugby ball": "橄榄球",
    "ski": "滑雪板",
    "soccer ball": "足球",
    "swimming trunks": "游泳裤",
    "tennis ball": "网球",
    "volleyball": "排球",
    "apple": "苹果",
    "artichoke": "洋蓟",
    "banana": "香蕉",
    "bell pepper": "灯笼椒",
    "cucumber": "黄瓜",
    "fig": "无花果",
    "head cabbage": "卷心菜",
    "lemon": "柠檬",
    "mushroom": "蘑菇",
    "orange": "橘子",
    "pineapple": "菠萝",
    "pomegranate": "石榴",
    "strawberry": "草莓"
}

export const SCENE_TRANSLATIONS = {
    "arena": "竞技场",
    "commercial": "商业",
    "domestic": "家居",
    "workplace": "办公",
    "athletic": "运动场",
    "building": "建筑物",
    "garden": "园地",
    "landscape": "风景",
    "public": "公共场所"
};
